import type { NextPage } from 'next'
import Head from 'next/head'


import Navbar from './../components/Navbar';
import HeroSection from './../components/HeroSection';



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Raw Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen'>
        <Navbar />
        <HeroSection />
      </main>
    </>
  );
};

export default Home
